name: Omega CI

on:
  push:
    branches: [ main, optimizing ]
  pull_request:
    branches: [ main, optimizing ]

jobs:
  build:
    name: 'Building Omega Project'
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
          MSSQL_PID: 'Developer'
          MSSQL_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
        options: --health-cmd='sqlcmd -S localhost -U sa -P ${MSSQL_PASSWORD} -Q "SELECT 1" || exit 1' --health-interval=10s --health-timeout=5s --health-retries=5
    
    steps:
      - name: 'Checkout Project'
        uses: actions/checkout@v2
      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.x
          
      - name: Create Database
        run: sqlcmd -S 127.0.0.1 -U sa -P ${{ secrets.MSSQL_SA_PASSWORD }} -Q"CREATE DATABASE OmegaUnitTests"
        
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        env:
          SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
        run: dotnet test --no-build --verbosity normal